### ISSUE TITLE
Typographical errors

### ISSUE THREAD

**Issue by ReliableNarrator** [nergantre/nightgamesmod#12]
- Game doesn't report the reason for Willpower loss when Charmed.
- NPC usage of Foot Smother & Foot Worship still talk about the wrong person.
- Drain has a couple typos: "vaginalmuscles" and "you realize your are"
- Dildo: "Angel slip it into your slit."
- "Reyka's imp grabs your socks and yanks it off."
- Using Frottage while wearing a strap-on says you use your dick.
- Ass Fuck capitalizes "Strap On" unnecessarily.
- Reyka using Tail Peg while sitting on your face says she hugs you from behind and that her tail tickles your prostate even as a female character. It also switches to the past tense for the second half of the description.
- Escape sometimes tells you that your captor catches you by your protruding penis even when you don't have a penis.
- "You use Force Masturbation. Cassie's none was pleasured by Cassie's hands"
- Using Force Pain says you order your victim to run into the nearest wall, even if you're sitting on them or otherwise restraining them.
- Dodging Cock Growth while being sat on (face, but maybe other positions as well) says you dodge out of the way.
- Wild Ride refers to a dick and says it drives both of you towards orgasm when you're using a strap-on.
- The Pull Out description (from the Ass Fuck stance) refers to a dick when it's really a strap-on. 
- Same thing as above when someone struggles out of the Ass Fuck stance.
- Face Fuck refers to strap-ons as dicks.
- After Cassie or Kat has beaten you and you masturbate with them still in the room, it says they watch you jerk off, even when you only have a pussy. Also sometimes says it multiple times.
- Being on the receiving end of Stomp, Flick, and Knee (when the PC is on the ground) refer to non-existent "jewels" and "balls".
- Undress is missing a period.
- "Samanthastumbles into range of the fetish totem." when triggering a tentacle trap.

**Comment by ReliableNarrator** [comment]
- Your non-existent boner can spring out when your pants/strap-on is torn off.
- An NPC surrendering says "she quickly find herself at the edge".
- The texts for collecting wisps and assorted juices in bottles are all missing periods.
- The flavor texts for drinking bottles of wisps and juices are missing a bunch of periods. The one for drinking Raw Aether is missing a verb ("You a bottle of Raw Ather").
- Samantha's text for getting naked has a superfluous quotation mark at the start.
- The Illusion trap with the beautiful naked woman who kisses you says she slips her hand "between you" instead of "between your legs". It also mentions your "very real" erection, even when it's not real at all.

**Comment by charrednewth** [comment]
Drain has a couple typos: "vaginalmuscles" and "you realize your are" - dibs & done
https://github.com/charrednewth/nightgamesmod/blob/master/NightgamesMod/nightgames/skills/Drain.java

**Comment by charrednewth** [comment]
Game doesn't report the reason for Willpower loss when Charmed. 
- dibs & done (also, just realized commit is auto-referenced. I won't double-link again)

**Comment by charrednewth** [comment]
Dibd & done: Dildo: "Angel slip it into your slit."

**Comment by nergantre** [comment]
You might want to pull the source, I actually fixed the charmed and dildo ones. woops.

**Comment by charrednewth** [comment]
Dibs & done - Ass Fuck capitalizes "Strap On" unnecessarily. Edit: woops x 2

**Comment by charrednewth** [comment]
woops+1 : installing githhub desktop to resolve conflicts... I guess I'll leave the github grown-ups alone tonight and figure how this *%é$$ works :(

**Comment by nergantre** [comment]
You don't need to do that to resolve conflicts, you can do it manually.

Just search for <<<<<< in the files that have conflicts, edit them until it makes sense, then add it back and commit.

**Comment by charrednewth** [comment]
woops -1 :) done (alleluja!)
Dibs & done: "Samanthastumbles into range of the fetish totem." when triggering a tentacle trap.
Dibs & done: Undress is missing a period.

@conflicts: You mean I could have done the same with online Github? Oh well, I didn't know how to anyway, and I didn't want to break your commits...
