### ISSUE TITLE
You can buy multiple strap-ons, though they never get used up.

### ISSUE THREAD

**Issue by ReliableNarrator** [nergantre/nightgamesmod#24]

**Comment by nergantre** [comment]
Hmmm I don't _really_ think this is an issue. You may want multiple in the future. What would you like here? that it sometimes breaks?

**Comment by charrednewth** [comment]
https://github.com/charrednewth/nightgamesmod/commit/595add86ca59f7c101e1bf4558c18bc11b1b005c

<spot Nergantre's reply> Woops... Or not?

**Comment by nergantre** [comment]
Eh that's fine, I just didn't want to take the time to do it :P

**Comment by nergantre** [comment]
woops closed by accident

**Comment by ReliableNarrator** [comment]
I only bring it up for the sake of polish. A player noticing they have the option to buy more than one strap-on will logically assume there must be some reason to do so, and I don't see the reasoning behind allowing them to keep dumping money into it only for them to eventually find out it was pointless and a waste of money. It's not really an issue because money is easy to come across and I doubt anyone will buy more than 2-5 before they find out what (doesn't) consume them, but if there's no apparent reason for being able to have multiple strap-ons, why allow it?

**Comment by charrednewth** [comment]
Dildos are used for Cassie's rituals, for instance. 
My changes to XXXstore made getting mouthPussy impossible if you have upgraded your dildo at the workshop.

We might expect some more spare toys to have future uses.
