### ISSUE TITLE
Flash of pink light trap not functioning and not being consumed when triggered

### ISSUE THREAD

**Issue by ReliableNarrator** [nergantre/nightgamesmod#27]
I don't know causes the text "There's a flash of pink light and Samantha flushes with arousal" to appear, but it's missing a period. As well, choosing to attack her simply prompts you to Fight or Flee rather than going straight into battle, as with the other traps. This may have come from an Illusion or Tentacle Trap, but didn't consume the trap when I chose to run away from her.

**Comment by charrednewth** [comment]
Illusion trap - dibs on text.
https://github.com/charrednewth/nightgamesmod/commit/2c924dc4aea1f1604fb2d5cacbc2315523950b10

Unsure about traps suposed to be expandable or permanent
