### ISSUE TITLE
You can rarely get free tentacle traps when moving between rooms

### ISSUE THREAD

**Issue by ReliableNarrator** [nergantre/nightgamesmod#28]
I've had a couple of games where it occurred consistently, but reproduction is tricky because people keep trying to fuck me while I'm debugging. I think it may occur when you place all of your available traps down in one room and then move to another room that can be trapped (like from Dorm to Shower). In related happenings, you can place multiples of the same trap in the same location, and they appear to all be used up when one is triggered.

**Comment by charrednewth** [comment]
Extra totems: probably from a cache; that's an issue if the cache text doesn't show for some reason.

Multiple traps: haven't looked into it yet

**Comment by ReliableNarrator** [comment]
I don't think they're coming from invisible caches because it worked pretty consistently when I kept moving back and forth from the Shower to the Dorm, but I'll keep that in mind from now on.
