### ISSUE TITLE
pussyTraining3 should add a value of .9 instead of .7

### ISSUE THREAD

**Issue by La-Li-Lu-Le-Lo** [nergantre/nightgamesmod#48]
[https://github.com/nergantre/nightgamesmod/blob/d8b2e9c9d4be246a44594a404427bc49f8c4ef47/NightgamesMod/nightgames/characters/body/PussyPart.java](https://github.com/nergantre/nightgamesmod/blob/d8b2e9c9d4be246a44594a404427bc49f8c4ef47/NightgamesMod/nightgames/characters/body/PussyPart.java)

_pleasureMod += self.has(Trait.pussyTraining1) ? .5 : 0;
pleasureMod += self.has(Trait.pussyTraining2) ? .7 : 0;
**pleasureMod += self.has(Trait.pussyTraining3) ? .7 : 0;**_
- pussyTraining3 should add a value of .9 instead of .7

**Comment by nergantre** [comment]
This is not a bug, the values are cumulative
