### ISSUE TITLE
Feature/bugfix priorities?

### ISSUE THREAD

**Issue by Ryplinn** [nergantre/nightgamesmod#49]
Hello @nergantre, @dndw, and other contributors,

What sorts of features or bugfixes are you most interested in for nightgames?

I've been having a blast writing infrastructure improvements like in #47, and I'd like to do more. I'm thinking of making the built-in NPCs work more like custom NPCs, so we don't have to recompile to fiddle with their stats, or making traits' effects not spread out over the whole codebase.

I'm open to suggestions, and certainly don't want to muck with anything someone's already working on.

Thanks!

**Comment by dndw** [comment]
I, for one, don't have any immediate priorities. In the rare moments that I have the time at present I'm working on the addictions for the remaining characters, and after that I'll be looking to improve the AI. If you want to help out, do whatever you like. Centralizing traits certainly sounds good, though, if ambitious.

**Comment by nergantre** [comment]
since this was a while ago, going to mark this as closed for now
