### ISSUE TITLE
Start Config "level" is adjusting Money instead.

### ISSUE THREAD

**Issue by bbob1980** [nergantre/nightgamesmod#50]
When creating my own version of NewGame+ I could not get the starting level to change. To troubleshoot, I copied the default config and renamed it, then just added "level":7 to the player config. It starts me with $7 and Lvl:1
[High Level.zip](https://github.com/nergantre/nightgamesmod/files/322417/High.Level.zip)

**Comment by dndw** [comment]
You're right, it's a copy-paste error.
For reference: CharacterConfiguration#apply, line 74

I'll fix this for the next release
